version: "3"
services:
  valheim:
    image: mbround18/valheim:latest
    ports:
      - 2456:2456/udp
      - 2457:2457/udp
      - 2458:2458/udp
    env_file:
      - env.list
    volumes:
      - /valheim/saves:/home/steam/.config/unity3d/IronGate/Valheim
      - /valheim/valheim_plus.cfg:/home/steam/valheim/BepInEx/config/valheim_plus.cfg