
name: Testing for Cloudheim

on:
  workflow_dispatch:

jobs:
  shutdown:
    name: Shutdown
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_CLI_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_CLI_KEY }}
          aws-region: us-east-1

      - name: Get EC2 Instance
        id: ec2
        run: |
          ip=`aws ec2 describe-instances --filters "Name=instance-type,Values=t3a.medium" --query "Reservations[].Instances[].PublicIpAddress" --output text`
          if [ -z $ip ]; then
            echo "ip is ${ip}"
          else
            echo "no instance running"
          fi



